<a href="https://colab.research.google.com/github/AshaRaniKulhade/Assignments/blob/main/Pandas_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

In [5]:
# read Travel_data excel file and create dataframe of number_of_arrival sheet
df = pd.read_excel("/content/drive/MyDrive/AI_ML/travel_data.xls",sheet_name="number_of_arrival",header=3,index_col=False,keep_default_na=True)
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,World,WLD,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,...,8.975338e+08,9.563723e+08,9.975553e+08,1.054602e+09,1.106732e+09,1.159450e+09,1.206216e+09,1.250468e+09,1.341457e+09,NaN
1,High income,HIC,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,...,5.483952e+08,5.794189e+08,6.058485e+08,6.320718e+08,6.635699e+08,7.053862e+08,7.386434e+08,7.751152e+08,8.212955e+08,NaN
2,OECD members,OED,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,...,5.016400e+08,5.216800e+08,5.454750e+08,5.637250e+08,5.921553e+08,6.302726e+08,6.641770e+08,6.873700e+08,7.387490e+08,NaN
3,Post-demographic dividend,PST,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,...,4.944450e+08,5.187433e+08,5.428600e+08,5.691869e+08,5.987758e+08,6.194239e+08,6.475276e+08,6.862630e+08,7.311272e+08,NaN
4,Europe & Central Asia,ECS,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,...,4.681120e+08,4.805914e+08,5.127784e+08,5.386314e+08,5.677226e+08,5.797844e+08,6.038805e+08,6.159794e+08,6.695441e+08,NaN

In [6]:
# read Travel_data excel file and store sheet data in different DataFrame
listofsheets = ['number_of_arrival','number_of_departure','expenditure for travel item','receipts for travel items','population','GDP']
# read all sheets from list into an different data frames
df_no_of_arrival,df_no_of_depature,df_expend_for_travel_item,df_receipts_for_travel,df_population,df_gdp = pd.read_excel("/content/drive/MyDrive/AI_ML/travel_data.xls", sheet_name= listofsheets,header=3).values()

#To show all columns of dataset.
pd.set_option('display.max_columns', None)

# show Top 5 records
df_no_of_arrival.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,World,WLD,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.239096e+08,5.545516e+08,5.843048e+08,6.022473e+08,6.272079e+08,6.773870e+08,6.782462e+08,6.984316e+08,6.890717e+08,7.614683e+08,8.087742e+08,8.570887e+08,9.201755e+08,9.363609e+08,8.975338e+08,9.563723e+08,9.975553e+08,1.054602e+09,1.106732e+09,1.159450e+09,1.206216e+09,1.250468e+09,1.341457e+09,NaN
1,High income,HIC,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.810508e+08,3.962287e+08,4.172100e+08,4.315233e+08,4.476925e+08,4.750799e+08,4.664505e+08,4.726940e+08,4.648900e+08,4.964440e+08,5.228668e+08,5.514283e+08,5.778505e+08,5.766349e+08,5.483952e+08,5.794189e+08,6.058485e+08,6.320718e+08,6.635699e+08,7.053862e+08,7.386434e+08,7.751152e+08,8.212955e+08,NaN
2,OECD members,OED,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.585940e+08,3.731950e+08,3.908013e+08,4.035437e+08,4.151737e+08,4.402514e+08,4.293773e+08,4.332865e+08,4.271157e+08,4.508724e+08,4.782050e+08,4.988310e+08,5.231530e+08,5.239680e+08,5.016400e+08,5.216800e+08,5.454750e+08,5.637250e+08,5.921553e+08,6.302726e+08,6.641770e+08,6.873700e+08,7.387490e+08,NaN
3,Post-demographic dividend,PST,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.291888e+08,3.429809e+08,3.659201e+08,3.780410e+08,3.909029e+08,4.177407e+08,4.143457e+08,4.218814e+08,4.163881e+08,4.452650e+08,4.702420e+08,4.959140e+08,5.213200e+08,5.192565e+08,4.944450e+08,5.187433e+08,5.428600e+08,5.691869e+08,5.987758e+08,6.194239e+08,6.475276e+08,6.862630e+08,7.311272e+08,NaN
4,Europe & Central Asia,ECS,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.955132e+08,3.116283e+08,3.366543e+08,3.468680e+08,3.551063e+08,3.830515e+08,3.841048e+08,3.954744e+08,3.982307e+08,4.165115e+08,4.396863e+08,4.629065e+08,4.904482e+08,4.932211e+08,4.681120e+08,4.805914e+08,5.127784e+08,5.386314e+08,5.677226e+08,5.797844e+08,6.038805e+08,6.159794e+08,6.695441e+08,NaN

In [7]:
# finding Number of missing values in each columns
df_no_of_arrival.isnull().sum()

Country Name        0
Country Code        0
Indicator Name      0
Indicator Code      0
1960              264
                 ...
2014               29
2015               28
2016               34
2017               49
2018              264
Length: 63, dtype: int64

In [8]:
print("Number of Rows in this dataset:-",df_no_of_arrival.shape[0])
print("Number of Columns in this dataset:-",df_no_of_arrival.shape[1])

Number of Rows in this dataset:- 264
Number of Columns in this dataset:- 63

In [22]:
df_no_of_arrival.bfill(axis=1)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,World,WLD,"International tourism, number of arrivals",ST.INT.ARVL,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,523909597.4811,554551599.274845,584304845.206599,602247337.899806,627207864.916467,677386990.330029,678246237.594481,698431588.301475,689071739.21153,761468261.168331,808774225.286775,857088654.563029,920175482.377196,936360913.440568,897533847.971687,956372259.67436,997555261.479495,1054602152.040613,1106732071.671006,1159450156.342449,1206215744.423386,1250467517.255382,1341456973.643252,NaN
1,High income,HIC,"International tourism, number of arrivals",ST.INT.ARVL,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,381050772.797657,396228682.240083,417210037.551296,431523260.72369,447692506.252486,475079867.032342,466450544.626331,472694012.067886,464889951.031296,496443969.35242,522866751.229243,551428259.047708,577850532.182156,576634904.543285,548395233.840017,579418921.504101,605848548.037426,632071775.74476,663569908.733594,705386216.469399,738643409.803597,775115157.738526,821295509.068955,NaN
2,OECD members,OED,"International tourism, number of arrivals",ST.INT.ARVL,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,358594011.545025,373195012.845386,390801343.934463,403543731.632901,415173735.340299,440251430.748564,429377297.295877,433286526.275894,427115685.502021,450872414.736632,478205000.0,498831000.0,523153000.0,523968000.0,501640000.0,521680000.0,545475000.0,563725000.0,592155300.0,630272600.0,664177000.0,687370000.0,738749000.0,NaN
3,Post-demographic dividend,PST,"International tourism, number of arrivals",ST.INT.ARVL,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,329188823.394738,342980932.599758,365920109.233493,378040977.884387,390902896.493441,417740688.888107,414345739.790387,421881407.133912,416388107.577973,445265030.657886,470242000.0,495914000.0,521320000.0,519256500.0,494445000.0,518743300.0,542860000.0,569186900.0,598775800.0,619423900.0,647527600.0,686263000.0,731127200.0,NaN
4,Europe & Central Asia,ECS,"International tourism, number of arrivals",ST.INT.ARVL,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,295513163.580618,311628300.036608,336654250.569372,346867957.055688,355106329.719766,383051537.194669,384104838.457619,395474416.213326,398230683.188459,416511482.361874,439686313.555552,462906516.065932,490448231.886891,493221112.669832,468111994.974335,480591397.951406,512778373.28911,538631437.742838,567722575.234444,579784449.311771,603880514.146686,615979433.539156,669544120.128371,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Syrian Arab Republic,SYR,"International tourism, number of arrivals",ST.INT.ARVL,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,815000.0,830000.0,891000.0,1267000.0,1386000.0,2100000.0,2192000.0,2661000.0,2598000.0,3399000.0,3571000.0,4231000.0,4158000.0,5430000.0,6092000.0,8546000.0,5070000.0,60000.0,81000.0,44000.0,25600.0,29000.0,2500.0,NaN
260,Turkmenistan,TKM,"International tourism, number of arrivals",ST.INT.ARVL,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,218000.0,217000.0,257000.0,300000.0,1386000.0,3400.0,5200.0,10800.0,8200.0,14800.0,11600.0,5600.0,8200.0,5430000.0,6092000.0,8546000.0,5070000.0,60000.0,81000.0,44000.0,25600.0,29000.0,2500.0,NaN
261,Virgin Islands (U.S.),VIR,"International tourism, number of arrivals",ST.INT.ARVL,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,373000.0,393000.0,422000.0,484000.0,546000.0,527000.0,520000.0,538000.0,563000.0,594000.0,571000.0,587000.0,574000.0,563000.0,572000.0,567000.0,619000.0,590000.0,615000.0,642000.0,667000.0,2500.0,NaN
262,Kosovo,XKX,"International tourism, number of arrivals",ST.INT.ARVL,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,454000.0,373000.0,393000.0,422000.0,484000.0,546000.0,527000.0,520000.0,538000.0,563000.0,594000.0,571000.0,587000.0,574000.0,563000.0,572000.0,567000.0,619000.0,590000.0,615000.0,642000.0,667000.0,2500.0,NaN
263,"Yemen, Rep.",YEM,"International tourism, number of arrivals",ST.INT.ARVL,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,61000.0,74000.0,80000.0,88000.0,58000.0,73000.0,76000.0,98000.0,155000.0,274000.0,336000.0,1061000.0,948000.0,1023000.0,1028000.0,1025000.0,829000.0,874000.0,990000.0,1017500.0,366700.0,667000.0,2500.0,NaN